apiVersion: v1
kind: Service
metadata:
  name: angular-client
  labels:
    service: angular-client
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4200
  selector:
    app: angular-client
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: angular-client-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: sagvii.com
    http:
      paths:
      - backend:
          serviceName: angular-client
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment                                          # 8
metadata:
  name: angular-client
spec:
  replicas: 2                                             # 9
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 10
    rollingUpdate: 
      maxUnavailable: 1                                   # 11
      maxSurge: 1                                         # 12
  template:
    metadata:
      labels:
        app: angular-client                                  # 13
    spec:
      containers:
        - image: giangnguyen/angular-client:dev #14
          imagePullPolicy: Always                         # 15
          name: angular-client
          ports:
            - containerPort: 4200